name: Java CI with Gradle

on:
  push:
    branches:  
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Permission
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew build -x test

  docker-upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Docker Build
      run: docker compose -f docker-compose-build.yml build
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/eurka-server:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/auth-server:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/user-server:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/performance-server:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/order-server:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/payment-server:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/queue-manage-server:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/client-channel-server:latest

  
